S/chron 5/notification module
GucioWons/chronica pull request #3
Opened 2024-03-09 06:30 UTC by BenzoEnzo

Zaimplementowano modul dostarczający funkcjonalność powiadomień. 
Modul sklada sie z 4 encji:
- Notification - Rodzic
- Message - dziedziczy po Notification
- Alert - dziedziczy po Notification
- Invitation - dziedziczy po Notification

- API:
- create
- read 
- delete 
- query(Zwraca listę rekordów spełniającą kryteria podane w requescie)

2024-03-10 13:54 UTC, GucioWons requested changes
Dobra, nie ma sensu na razie tego sprawdzać bardziej. Uwzględnij komentarze które dałem ci pod userem (gŁównie te z DTOsami i zwracanymi wartościami). Fajnie że użyłeś generycznych komponentów dla Notyfikacji, ALE mam parę pomysłów jak to zrobić lepiej:

- Zrób DTOsa NotificationDTO, po którym pola będą dziedziczyc pozostałe DTOsy
- Zrób NotificationMapperDTO, po którym pola będą dziedziczyć pozostałe mappery
- Dodaj te DTOsy i mappery do generyków - dzięki temu każdy serwis będzie zwracał Ci od razu przemapowane encje
- Po wprowadzeniu tych zmian będziesz mógł w notificationControllerze zwracać listę RÓZNYCH NotificationDTOsów - w responsie każda z notyfikacji będzie mogła mieć odpowiednie dla siebie pola, przez co na front będą trafiały wszyskie notyfikacje z potrzebnymi informacjami.

2024-03-10 13:54 UTC, GucioWons commented on notification/src/main/java/com/chronica/notification/data/entity/Invitation.java
> +public class Invitation extends Notification {
Do tego jeszcze przydałby się groupId

2024-03-10 13:54 UTC, GucioWons commented on notification/src/main/java/com/chronica/notification/data/entity/Invitation.java
> +    private Long invitationFromId;
to jest bardziej userFromId

2024-03-10 13:54 UTC, GucioWons commented on notification/src/main/java/com/chronica/notification/data/entity/Notification.java
> +    protected Long receiverId;
Bardziej userToId

2024-03-10 13:54 UTC, GucioWons commented on notification/src/main/java/com/chronica/notification/data/entity/Notification.java
> +public class Notification implements Serializable {
Dodałbym to jeszcze booleana seen

2024-03-10 13:54 UTC, GucioWons commented on notification/src/main/java/com/chronica/notification/controller/NotificationController.java
> +    @PostMapping(path = "/query-all")
Z tego co rozumiem, to chodzi tutaj o getAll? Jeśli tak to powinien być get, bez żadnej ściezki

2024-03-10 13:54 UTC, GucioWons commented on notification/src/main/java/com/chronica/notification/controller/NotificationController.java
> +    @PostMapping(path = "/create")
Post oznacza że tworzysz - nie ma sensu dodawania ścieżki

2024-03-10 13:54 UTC, GucioWons commented on notification/src/main/java/com/chronica/notification/controller/NotificationController.java
> +    @GetMapping(path = "/read/{id}")
get oznacza że getujesz - nie ma sensu dodawania read

2024-03-10 13:54 UTC, GucioWons commented on notification/src/main/java/com/chronica/notification/logic/NotificationApi.java
> +public class NotificationApi {
To na pewno zła nazwa

2024-03-15 18:11 UTC, BenzoEnzo commented on notification/src/main/java/com/chronica/notification/data/entity/Notification.java
> +public class Notification implements Serializable {
done

2024-03-15 18:12 UTC, BenzoEnzo commented on notification/src/main/java/com/chronica/notification/controller/NotificationController.java
> +    @PostMapping(path = "/create")
done

2024-03-15 18:12 UTC, BenzoEnzo commented on notification/src/main/java/com/chronica/notification/logic/NotificationApi.java
> +public class NotificationApi {
done

2024-03-15 18:12 UTC, BenzoEnzo commented on notification/src/main/java/com/chronica/notification/controller/NotificationController.java
> +    @GetMapping(path = "/read/{id}")
done

2024-03-15 18:21 UTC, BenzoEnzo commented on notification/src/main/java/com/chronica/notification/data/entity/Invitation.java
> +public class Invitation extends Notification {
done

2024-03-17 11:19 UTC, GucioWons requested changes

2024-03-17 11:19 UTC, GucioWons commented on notification/src/main/java/com/chronica/notification/controller/NotificationController.java
> +    @PostMapping(path = "/query-all")
Mapping do tego nadal jest zły, powinien być GET i brak patha

2024-03-17 11:19 UTC, GucioWons commented on notification/src/main/java/com/chronica/notification/controller/NotificationController.java
> +    public ResponseEntity<QueryNotificationDTO> queryNotices(@RequestBody QueryNotificationDTO filter){
Rzeczy takie jak page raczej podaje się w query paramsach. Do tego ta nazwa troche nie ma sensu. Mogłoby być coś w stylu getQueriedNotices

2024-03-17 11:19 UTC, GucioWons commented on notification/src/main/java/com/chronica/notification/data/constant/SortDirection.java
> +public enum SortDirection {
Czy jest sens tworzyć osobnego enuma skoro i tak wartością w nich jest enum Sort.Direction?

2024-03-17 11:19 UTC, GucioWons commented on notification/src/main/java/com/chronica/notification/data/dto/ErrorDTO.java
> +                       HttpStatus statusCode,
To było też w userze - po co zwracać statusCode w DTOsie skoro jest zwracany w requeście?

2024-03-17 11:19 UTC, GucioWons commented on notification/src/main/java/com/chronica/notification/data/entity/Message.java
> +    private Long messageFromId;
Tutaj powinno być user from id, tak jak w invitation - nazwa zmiennej nie mówi nam do czego odnośi się to id - może być fromUSer, fromGroup etc

2024-03-17 11:19 UTC, GucioWons commented on notification/src/main/java/com/chronica/notification/data/entity/Notification.java
> +    protected Long receiverId;
Tutaj tak jak w message i invitation powinna być utrzymana konwencja - zmienna powinna się nazywać userToId żeby wskazywała w jakim module i encji znajduje się ten "reciever"

2024-03-17 11:19 UTC, GucioWons commented on notification/src/main/java/com/chronica/notification/data/entity/Notification.java
> +    protected Boolean seen = false;
O booleanach obiektwych było już chyba w userze. Boolean obiektowy może być nullem, jeśli nie potrzebujemy wartości null jako seen albo deprecated(a raczej nie potrzebujemy), to lepiej dać zmienna prostą. Pomoże to uniknąć nullpointerów i problemów podczas migracji danych

2024-03-17 11:19 UTC, GucioWons commented on notification/src/main/java/com/chronica/notification/data/dto/NotificationDTO.java
> +public record NotificationDTO(
Nie o to mi chodziło w komentarzu o DTOsach. Możesz zrobić DTOsy AlertDTO, InvitationDTO, MessageDTO dziedziczące po tym DTOsie, tak żeby np AlertDTO nie zawierał niepotrzebnego userFromId. Wtedy będziesz mógł wszystkie te DTOsy wrzucić do jednej Listy <NotificationDTO>, a jackson je przemapuje z odpowiednimi wartościami.

2024-03-17 11:19 UTC, GucioWons commented on notification/src/main/java/com/chronica/notification/data/mapper/NotificationMapper.java
> +public class NotificationMapper {
Czy naprawdę potrzebujesz tyle kodu w tym mapperze? Mógłbyś to załatwić setterami lub builderem - zamiast tworzyć taką zawiłą logikę, po prostu ustawić wszystkie wymagane pola.

2024-03-17 11:19 UTC, GucioWons commented on notification/src/main/java/com/chronica/notification/data/mapper/NotificationMapper.java
> +        if(entity instanceof Message){
Sprawdzanie typów obiektów powinno być ostatecznością. Możesz to obejść w bardzo ładny sposób - w tym mapperze zostawić jedynie ustawianie zmiennych notyfikacji, utworzyć mappery do pozostałych typów i używać NotificationMappera do mapowania notyfikacji, a następnie dodac wartości potrzebne w pozostałych notyfikacjach. Myślę też, że notification type powinien być ustawiany na backendzie - najlepiej byłoby utworzyć kontrolery do każdego z rodzaju notyfikacji, endpointy i obsługiwać w nich ich tworzenie. Trzeba pamiętać że im bardziej rozwinięta będzie aplikacja, tym bardziej może się różnić logika tworzenia różnych powiadomień.

2024-03-17 11:19 UTC, GucioWons commented on notification/src/main/java/com/chronica/notification/logic/NotificationMasterService.java
> +    public ResponseEntity<NotificationDTO> createNotice(NotificationDTO request){
Twoja encja to nie notice, tylko notification. Do tego ResponseEntity nie powinien być użyty w warstwie biznesowej, tylko w kontrolerze. Tutaj powinieneś zwrócić NotificationDTO

2024-03-17 11:19 UTC, GucioWons commented on notification/src/main/java/com/chronica/notification/logic/NotificationMasterService.java
> +        final NotificationDTO response = notificationMapper.mappToDto(notification);
Niepotrzebne są te finale, tym bardziej że w przyszłości możesz chcieć coś zrobić np z nptification przed zapisem. Do tego ten kod dałoby się zrobic jednym ciągiem:
return notificationMapper.mapToDTO(
    notificationRepository .save(notificationMapper.mapToEntity(request)))

2024-03-17 11:19 UTC, GucioWons commented on notification/src/main/java/com/chronica/notification/logic/NotificationMasterService.java
> +        final Notification notification = notificationService.findById(id);
w tej metodzie to samo - te finale nie są potrzbne

2024-03-17 11:19 UTC, GucioWons commented on notification/src/main/java/com/chronica/notification/logic/NotificationMasterService.java
> +    public ResponseEntity<NotificationDTO> readNotice(Long id){
Nie czytasz notica tylko go getujesz. Read brzmi jakbyś go po prostu wczytywał,a nie zwracał

2024-03-17 11:19 UTC, GucioWons commented on notification/src/main/java/com/chronica/notification/logic/NotificationMasterService.java
> +        final NotificationDTO response = notificationMapper.mappToDto(notification);
Oczywiście finale niepotrzebne

2024-03-17 11:19 UTC, GucioWons commented on notification/src/main/java/com/chronica/notification/logic/NotificationMasterService.java
> +        return ResponseEntity
To też da się zrobić czytelnie w jednej linijce - return notificationMapper.maptoDTO(notificationService.findById(id))

2024-03-17 11:19 UTC, GucioWons commented on notification/src/main/java/com/chronica/notification/logic/util/PropertyTransfer.java
> +public class PropertyTransfer {
To powinien byc komponent wstrzyknięty do serwisu

2024-03-24 18:33 UTC, GucioWons requested changes

2024-03-24 18:33 UTC, GucioWons commented on notification/src/main/java/com/chronica/notification/controller/NotificationController.java
> +    @PatchMapping(path = "/{id}")
Patcha używa się raczej przy updatowaniu jakiejś pojedynczej rzeczy. W tym przypadku updatujesz cały obiekt więc powinien byc put

2024-03-24 18:33 UTC, GucioWons commented on notification/src/main/java/com/chronica/notification/data/constant/PriorityType.java
> +public enum PriorityType {
To powinno raczej być po prostu Priority. Ten enum to nie typ rpiorytetu tylko priorytet

2024-03-24 18:33 UTC, GucioWons commented on notification/src/main/java/com/chronica/notification/data/dto/AlertDTO.java
> +    private NotificationDTO baseData;
Powinno extendować NotificationDTO, ponieważ Alert to rozszerzony notification. Tak by było gdyby Notification było polem w Alercie

2024-03-24 18:33 UTC, GucioWons commented on notification/src/main/java/com/chronica/notification/data/dto/InvitationDTO.java
> +    private NotificationDTO baseData;
To samo co przy Alercie

2024-03-24 18:33 UTC, GucioWons commented on notification/src/main/java/com/chronica/notification/data/dto/MessageDTO.java
> +    private NotificationDTO baseData;
To samo co przy alercie

2024-03-24 18:33 UTC, GucioWons commented on notification/src/main/java/com/chronica/notification/data/dto/MessageDTO.java
> +
Ło kurwa ile enterów

2024-03-24 18:33 UTC, GucioWons commented on notification/src/main/java/com/chronica/notification/data/entity/Invitation.java
> +    private Long invitationFromUserId;
Ta nazwa na pewno jest zła. Jeśli chcesz utrzymać konwencję z notification to powinno być inviterId, ale ja jestem raczej za tym żeby to było userFromId/invitingUserId - jeśli użyjesz którejś z moich propozycji to musisz zmienić nazwę recieverId w notification

2024-03-24 18:33 UTC, GucioWons commented on notification/src/main/java/com/chronica/notification/data/entity/Message.java
> +
duuużo enterów

2024-03-24 18:33 UTC, GucioWons commented on notification/src/main/java/com/chronica/notification/data/entity/Notification.java
> +    public void setNotification(Notification notification) {
Ta klasa powinna śłużyć tylko jako entity - coś takiego to złamanie Single resposibility

2024-03-28 18:35 UTC, merged